# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IVFDF 2021
list-title: News
email: enquiries@ivfdf2021.org.uk
logo: assets/logo_large.png
description: >- # this means to ignore newlines until "baseurl:"
IVFDF is the 'Inter Varsity Folk Dance Festival' it is an exciting and dynamic festival held by a different university each year.
IVFDF has been running since 1951 and is the UK’s longest continually running folk festival.
A non-stop weekend of music and dance from the British Isles and beyond.
This year streamed straight to your home so we may even get some actual sleep this time!
baseurl: "/IVFDF2021" # the subpath of your site, e.g. /blog
url: "https://www.codersoffortune.net" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: IVFDF2021
#twitter_username: jekyllrb
#github_username:  jekyll
header_pages:
 - events.md
 - community.md
 - tickets.md
 - contact.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
